<a href="https://colab.research.google.com/github/abdullahkhan57721/Applied-Mathematical-Computation/blob/main/HW_2_(PLU_Decomposition).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Introduction to Applied Mathematical Computation
#HW-2
#Abdullah Khan

In [ ]:
import sympy as sym
from scipy import linalg as lin
import numpy as np

In [ ]:
#Question 2

#The augmented matrix A can be written as:
A = [[0,20,0,0,0,14],[20,0,48,20,16,92],[0,48,0,65,36,140.10],[0,20,65,0,35,87.75],[0,16,36,35,0,99.70]]

#Using sympy's Matrix function, we first recast A as a sympy matrix. Next, we use the rref function, we compute the reduced row echelon form of matrix A.
A = sym.Matrix(A)
A.rref()

(Matrix([
 [1, 0, 0, 0, 0,  0.5],
 [0, 1, 0, 0, 0, 7/10],
 [0, 0, 1, 0, 0,  1.0],
 [0, 0, 0, 1, 0,  1.5],
 [0, 0, 0, 0, 1, 0.25]]), (0, 1, 2, 3, 4))

In [ ]:
#Question 3(b)

#Let A be a square LU diagnalizable matrix. Then, L and U are both square matrices of the same dimension as A.
#Passing L and U as list (rows) of lists (elements in each row) and b as a list, we construct the following function that outputs the solution x to Ax = b.
def LUDecompSolution(L, U, b):
  #Determine the dimension of the solution space (and thereby the dimensions of L and U for Ax=b to be meaningful)
  n = len(b)
  #We solve for y in Ly=b. First, initialize a list y with the correct dimension and then we use the starred equation from page 6 of the notes.
  y = list(range(n))
  for k in list(range(0,n)):
    y[k] = b[k] #First term (first row)
    for i in list(range(0, k)): #Subtracting the summation with indices adjusted to start at 0
      y[k] = y[k] - (L[k][i]*y[i]) #Computing y[k] in increasing order of indices
      y[k] = y[k]/L[k][k] #Final division

  #Using the second starred equation from page 7 of the notes, we solve for x in Ax=b
  #Once again, we start by initializing a list x with the correct dimension.
  x = list(range(n))
  for k in range(0,n):
    x[n-1-k] = y[n-1-k] #First term (last row)
    for i in range (n-k, n):
      x[n-1-k] = x[n-1-k] - U[n-1-k][i]*x[i] #Computing x[k] in decreasing order of indices
    x[n-1-k] = x[n-1-k]/U[n-1-k][n-1-k] #Final division
  print(x)

#As a check, we use the b from part (a) to solve for x.
L = [[1,0,0,0],[-1,1,0,0],[2,-5,1,0],[-3,8,3,1]]
U = [[3,-7,-2,2],[0,-2,-1,2],[0,0,-1,1],[0,0,0,-1]]
b = [-9,5,7,11]
LUDecompSolution(L,U,b)

#For the b given in subparts (i) and (ii):
b_1 = [-1,1,6,3]
b_2 = [2,4,2,-1]
LUDecompSolution(L,U,b_1)
LUDecompSolution(L,U,b_2)

[3.0, 4.0, -6.0, -1.0]
[31.666666666666668, 16.0, 16.0, 24.0]
[155.83333333333334, 74.5, 99.0, 127.0]


In [ ]:
#Question 4(a)

#We find the PLU decomposition using scipy's lu function.

A = [[1,0,4,2],[-1,1,8,0],[-4,2,5,1],[0,2,-3,1]]
B = lin.lu(A) #Saving the returned (P,L,U) array to B
P_inv = B[0] #Saving P as P_inv so that PA = LU
P = lin.inv(P_inv) #Inverting P_inv to the correct P in PA = LU
L = B[1]
U = B[2]

print(P)
print(L)
print(U)

[[-0.  0.  1. -0.]
 [-0.  0.  0.  1.]
 [-0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]
[[ 1.    0.    0.    0.  ]
 [-0.    1.    0.    0.  ]
 [ 0.25  0.25  1.    0.  ]
 [-0.25  0.25  0.8   1.  ]]
[[-4.   2.   5.   1. ]
 [ 0.   2.  -3.   1. ]
 [ 0.   0.   7.5 -0.5]
 [ 0.   0.   0.   2.4]]


In [ ]:
#Question 4(b)

#Inputting the various matrices
A = [[1,0,4,2],[-1,1,8,0],[-4,2,5,1],[0,2,-3,1]]
P_inv = [[0., 0., 0., 1.],
      [0., 0., 1., 0.],
      [1., 0., 0., 0.],
      [0., 1., 0., 0.]]
P = lin.inv(P_inv)
L = [[ 1.  ,  0.  ,  0.  ,  0.  ],
        [-0.  ,  1.  ,  0.  ,  0.  ],
        [ 0.25,  0.25,  1.  ,  0.  ],
        [-0.25,  0.25,  0.8 ,  1.  ]]
U = [[-4. ,  2. ,  5. ,  1. ],
        [ 0. ,  2. , -3. ,  1. ],
        [ 0. ,  0. ,  7.5, -0.5],
        [ 0. ,  0. ,  0. ,  2.4]]

#Mulitlying the matrices
PA = np.dot(P,A)
LU = np.dot(L,U)

#Printing PA and LU to verify that they are equal.
print(PA)
print(LU)

#They are indeed equal.

In [ ]:
#Question 4(c)
b_old = [31,30,21,-7]
c_old = [1545,-70,816,868]

#We multiply each b_i with P
b_new = np.dot(P, b_old)
c_new = np.dot(P, c_old)

#Lastly, we solve Ax = b as PA x = Pb or LU x = (Pb).
z_1 = LUDecompSolution(L, U, b_new)
z_2 = LUDecompSolution(L, U, c_new)

[0.9999999999999998, -0.9999999999999996, 4.0, 6.999999999999999]
[-11.0, 15.0, -12.0, 802.0]
